# Generated by Django 6.0.1 on 2026-01-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
