# Generated by Django 6.0 on 2026-01-24 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_location_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='image_url',
        ),
    ]
