# Generated by Django 6.0 on 2026-02-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_clusterhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='adventure_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='altitude_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='culture_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nature_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='top_match_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
